### ISSUE TITLE
Hostname should default to "localhost"

### ISSUE THREAD

**Issue by whatyouhide** [ericmj/postgrex#160]
Right now, it doesn't default to anything :(

**Comment by ericmj** [comment]
Postgrex 0.11.0 and Ecto master.

Error:
```
20:05:42.086 [error] GenServer #PID<0.15566.0> terminating
** (KeyError) key :hostname not found in: [types: true, name: Dumblr.Repo.Pool, otp_app: :dumblr, repo: Dumblr.Repo, adapter: Ecto.Adapters.Postgres, username: "postgres", password: "postgres", database: "dumblr", pool_timeout: 5000, timeout: 15000, pool: DBConnection.Poolboy, adapter: Ecto.Adapters.Postgres, username: "postgres", password: "postgres", database: "dumblr", extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432]
    (elixir) lib/keyword.ex:324: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:37: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:114: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:623: Connection.enter_connect/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: nil
State: nil
```

/cc @fishcakez

**Comment by fishcakez** [comment]
This is an issue with the postgres adapter in Ecto master and not an issue
with postgrex. The adapter needs to call the default options function when
it returns the db_connection callback module and options. This should be
done in Ecto.Adapters.Postgres.Connection.connection/1 and the function is
in Postgrex.Utils but I forget the name, Andrea added it when he moved the
notify API to its own process. Its possible we have some other issues in
Ecto master because we don't call this function.

On 11 February 2016 at 19:08, Eric Meadows-Jönsson <notifications@github.com
