### ISSUE TITLE
Do something other than throw when no extension found for OID

### ISSUE THREAD

**Issue by robconery** [ericmj/postgrex#162]
Right now if I have `tsvector` in my table (which is common) or, more likely, I return a custom type for a query, [Postgrex throws](https://github.com/ericmj/postgrex/blob/master/lib/postgrex/types.ex#L293):

```
     ** (ArgumentError) no extension found for oid `3614`
     stacktrace:
       (postgrex) lib/postgrex/types.ex:298: Postgrex.Types.fetch!/2
       (postgrex) lib/postgrex/types.ex:222: Postgrex.Types.decoder/2
```

I'm still quite new to the Erlang world, but from my experience over the years in other platforms - libraries shouldn't throw (especially drivers) unless they quite literally cannot complete an operation. In this case Postgrex can complete the *query*, it just can't decode a given result.

I'd like to strongly suggest that throwing in this way means I have to resort to pure SQL to get around this - either by writing a view, function, or custom query. I would prefer quite a few other scenarios - one being that you simply return `nil` instead of throwing. 

I know that I can write an Extension to get around this, so I can decode the types as I want. I'd like to suggest this is cumbersome, especially for database aficionados (like myself) who embrace all type richness Postgres has to offer.

**Comment by josevalim** [comment]
Thanks @robconery!

I would really avoid to return `nil` on those cases. Imagine a developer trying to work with a new type and they start getting nil. I would look at it and think: "is it `NULL` in the database?! No, it isn't. So why am I getting nil? Is it a Postgrex bug? Likely."

In other words, you know what you want to do (return nil) because the error message told you so. If we remove this information, most people won't know what to do.

Given we shouldn't use `nil` because it is ambiguous and because we would just throw away information, I'd rather return something like `Postgrex.UnkownOID{value: <<>>, oid: ...}` but I am not sure if I would make it the default. Maybe an option?

**Comment by robconery** [comment]
Perfect! A struct or a simple `{:unknown, oid: ..., value: ...}` would be swell. Another thought would be to decode as a string - which is what a lot of other drivers do. I don't know if this is a simple option... but thanks for thinking on it :).

**Comment by josevalim** [comment]
Since we use the binary protocol, we are getting a binary... so I would wrap it as it is not anything that would make sense to your application unless you decode it (which then would effectively solve the problem).

**Comment by robconery** [comment]
Yeah I figured. Still bumbling around trying to figure out the binary stuff... but the *super cool* thing here is that we could use this *right now* with Moebius and things we're trying to do with various datatypes.

**Comment by fishcakez** [comment]
It is possible to do this _right now_ using an extension:
```elixir
defmodule Moebius.TSVector do
  @behaviour Postgrex.Extension

  def init(_, _), do: nil

  def matching(_), do: [output: "tsvectorout"]

  def format(_), do: :text

  def encode(_, text, _, _) when is_binary(text), do: text

  def decode(_, text, _, _), do: text
end
```

You could list __all__ outputs (not just `"tsvectorout"`) that Moebius wishes to handle that Postgrex does not by default. It may be easier to do this by type, e.g. `[type: "tsvector"]`. Postgrex uses the wire encoding (output/send), rather than the internal type (type) because that the is data received by postgrex.

Of course to produce a term that is easy to "use", one would need to use the binary format, rather than text. However that requires knowing how to encode/decode the binary format of a tsvector.

**Comment by robconery** [comment]
Wow. @fishcakez you're a freaky genius! This works perfectly - thank you!

**Comment by robconery** [comment]
I'm going to close this for now - this is a fine solution!

**Comment by fishcakez** [comment]
@robconery if you need some more help with Moebius's extensions feel free to mention me in a PR or contact me on IRC.

**Comment by robconery** [comment]
Cheers - thanks :)
