### ISSUE TITLE
Move after_connect logic to callback

### ISSUE THREAD

**Issue by josevalim** [ericmj/postgrex#165]
/cc @fishcakez

**Comment by fishcakez** [comment]
If we bootstrap in `after_connect` using the current type server the `after_connect` process will be monitored and not the connection process. Even if we update the type server to switch monitors on successful bootstrap there still exists a race condition where the bootstrap is a successful but the connection process times out. In this situation the connection process is monitored by the type server and tries to connect again - resulting in at least another monitor. This could easily occur if `after_connect` is used to run custom queries as the connection process has to wait for the full `after_connect` to finish before it gets the updated state.

In fact these monitors are never cleaned up once bootstrap is successful. This means we are currently leaking monitor references every time we disconnect and reconnect on the same connection! This occurs on checkout timeout, ownership timeout and tcp disconnect.

The easiest way to solve this is to use links instead of monitors as 1 process is always 1 link no matter how many times `link/1` is called. This approach will mean that connections will exit if the type server goes down. This is ok because their type table is lost.

This blocks Ecto 2.0. We will also need to use a new release of postgrex for Ecto 1.1.

**Comment by fishcakez** [comment]
I have started on this

**Comment by fishcakez** [comment]
Fixed in 6f858c5fd2aa92ca83f74c941bf5f56202ab2dd2 but using a different approach. Instead we use `:timer` to shutdown the socket if we timeout during handshake. This keeps the code simpler and means we don't need to send auth information to a task that will log its arguments on error. That commit fixes the issue with the type server leak too.
